spring.application.name=end-project




spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.hibernate.ddl-auto=
spring.jpa.open-in-view=
spring.flyway.enabled=
spring.flyway.locations=

app.jwt.secret= 
app.jwt.expiration-seconds=
app.bootstrap.admin.email=
app.bootstrap.admin.password=
app.bootstrap.admin.display-name=


spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=

app.email.from=
app.email.enabled=