spring.application.name=end-project




spring.datasource.url=jdbc:postgresql://localhost:5432/javalearning
spring.datasource.username=postgres
spring.datasource.password=chandu
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret= your-very-long-secret-key-at-least-32-characters
app.jwt.expiration-seconds=3600
app.bootstrap.admin.email=chandu@divami.com
app.bootstrap.admin.password=CharanAparna@2022
app.bootstrap.admin.display-name=chandu


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandu@divami.com
spring.mail.password=jhhpublodzlojgqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.email.from=chandu@divami.com
app.email.enabled=true